# Coding Temple's Data Analytics Program  
---
# Advanced Python 1 - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [1]:
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [2]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [6]:

my_array = np.random.randint(0, 101, (5, 3))
print(my_array)



[[17 54 48]
 [65 44 47]
 [70 96 19]
 [39 63  3]
 [ 1 77 12]]


### 1.2 Solution - Run the following cell to check your answer.

In [7]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert my_array.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [10]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]

height_sq = (np.array(height)) **2
weight_conv = (np.array(weight)) * 703

bmi = (weight_conv / height_sq)
print(bmi.astype(int))



[39  8 16 14]


### 1.3 Solution: Run the following cell to check your answer.

In [11]:
# DO NOT EDIT THIS CELL
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'


### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [19]:
def my_func(x,y):
    matrix = np.random.randint(0,10, (x,y))
    return matrix 

print(my_func(8,8))


[[7 3 1 6 3 9 0 3]
 [4 3 1 7 5 4 5 9]
 [8 7 8 1 3 0 3 3]
 [4 6 0 3 5 6 2 6]
 [8 5 1 8 8 3 1 0]
 [4 9 7 3 0 8 1 7]
 [6 1 3 1 8 4 0 3]
 [2 3 7 6 2 4 5 9]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [26]:
matrix = np.random.randint(0,10, (8,8))

print(matrix[0])
print(f"\n{matrix}")


[8 6 2 2 9 9 2 4]

[[8 6 2 2 9 9 2 4]
 [8 7 8 8 4 5 9 1]
 [3 6 3 8 8 8 7 9]
 [8 2 2 8 8 9 8 4]
 [4 7 8 3 0 6 6 5]
 [0 0 9 0 7 3 2 1]
 [5 6 8 9 9 2 5 7]
 [3 2 2 4 6 2 8 3]]


In [27]:
print(matrix [:, -1])
print(f"\n{matrix}")


[4 1 9 4 5 1 7 3]

[[8 6 2 2 9 9 2 4]
 [8 7 8 8 4 5 9 1]
 [3 6 3 8 8 8 7 9]
 [8 2 2 8 8 9 8 4]
 [4 7 8 3 0 6 6 5]
 [0 0 9 0 7 3 2 1]
 [5 6 8 9 9 2 5 7]
 [3 2 2 4 6 2 8 3]]


In [31]:
print(matrix [3:5, 2])
print(f"\n{matrix}")

[2 8]

[[8 6 2 2 9 9 2 4]
 [8 7 8 8 4 5 9 1]
 [3 6 3 8 8 8 7 9]
 [8 2 2 8 8 9 8 4]
 [4 7 8 3 0 6 6 5]
 [0 0 9 0 7 3 2 1]
 [5 6 8 9 9 2 5 7]
 [3 2 2 4 6 2 8 3]]


In [32]:
print(matrix * 2)
print(f"\n{matrix}")


[[16 12  4  4 18 18  4  8]
 [16 14 16 16  8 10 18  2]
 [ 6 12  6 16 16 16 14 18]
 [16  4  4 16 16 18 16  8]
 [ 8 14 16  6  0 12 12 10]
 [ 0  0 18  0 14  6  4  2]
 [10 12 16 18 18  4 10 14]
 [ 6  4  4  8 12  4 16  6]]

[[8 6 2 2 9 9 2 4]
 [8 7 8 8 4 5 9 1]
 [3 6 3 8 8 8 7 9]
 [8 2 2 8 8 9 8 4]
 [4 7 8 3 0 6 6 5]
 [0 0 9 0 7 3 2 1]
 [5 6 8 9 9 2 5 7]
 [3 2 2 4 6 2 8 3]]


In [33]:
print(matrix / 3)
print(f"\n{matrix}")

[[2.66666667 2.         0.66666667 0.66666667 3.         3.
  0.66666667 1.33333333]
 [2.66666667 2.33333333 2.66666667 2.66666667 1.33333333 1.66666667
  3.         0.33333333]
 [1.         2.         1.         2.66666667 2.66666667 2.66666667
  2.33333333 3.        ]
 [2.66666667 0.66666667 0.66666667 2.66666667 2.66666667 3.
  2.66666667 1.33333333]
 [1.33333333 2.33333333 2.66666667 1.         0.         2.
  2.         1.66666667]
 [0.         0.         3.         0.         2.33333333 1.
  0.66666667 0.33333333]
 [1.66666667 2.         2.66666667 3.         3.         0.66666667
  1.66666667 2.33333333]
 [1.         0.66666667 0.66666667 1.33333333 2.         0.66666667
  2.66666667 1.        ]]

[[8 6 2 2 9 9 2 4]
 [8 7 8 8 4 5 9 1]
 [3 6 3 8 8 8 7 9]
 [8 2 2 8 8 9 8 4]
 [4 7 8 3 0 6 6 5]
 [0 0 9 0 7 3 2 1]
 [5 6 8 9 9 2 5 7]
 [3 2 2 4 6 2 8 3]]


In [35]:
print(matrix[0] + 12)
print(f"\n{matrix}")

[20 18 14 14 21 21 14 16]

[[8 6 2 2 9 9 2 4]
 [8 7 8 8 4 5 9 1]
 [3 6 3 8 8 8 7 9]
 [8 2 2 8 8 9 8 4]
 [4 7 8 3 0 6 6 5]
 [0 0 9 0 7 3 2 1]
 [5 6 8 9 9 2 5 7]
 [3 2 2 4 6 2 8 3]]


In [36]:
print(matrix[:, 0].mean())


4.875


In [37]:
matrix = np.sort(matrix, axis=None)
matrix = matrix [2:]
print(np.median(matrix))


6.0


In [39]:
matrix = np.random.randint(100, size=(8, 8))
                           
print(np.std(matrix[0:3,:]))


23.197483999108368


In [40]:
greater = matrix[:, 1] > 25
print(matrix[greater])


[[41 68 96 56 91  8 92 67]
 [17 31 69 54 87 49 76 51]
 [81 47 34 35 70 81 56 60]
 [ 9 61 69 71  9 89 18 13]
 [27 32 94 17 69 43 89 63]
 [34 85 15 18 55 15 72 54]
 [39 84 35 62 11 62 34 39]]


In [41]:
less = matrix < 40
print(matrix[less])

[ 8 17 31 34 35  9  9 18 13 27 32 17 34 15 18 15 33 12  6 12  8  0 39 35
 11 34 39]


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [ ]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.5

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])